config/routes.rb
Rails.application.routes.draw do

  root 'login#dispatcher'

  get '/login/form', to: 'login#form'
  post '/login/sign_in', to: 'login#sign_in'
  post '/login/sign_up', to: 'login#sign_up'
  get '/logout', to: 'login#sign_out'

  get '/conferences/home', to: 'conferences#home'
  get '/conferences/feedback', to: 'conferences#feedback'
  post '/conferences/feedback', to: 'conferences#feedback_update'
  get '/conferences/:id', to: 'conferences#details'
  get '/conferences/:id/toggle_attend', to: 'conferences#toggle_attend'

  get '/suggestions/home', to: 'suggestions#home'
  post '/suggestions/new', to: 'suggestions#new'
  get '/suggestions/:id', to: 'suggestions#details'
  get '/suggestions/:id/toggle_like', to: 'suggestions#toggle_like'

  get '/backoffice/home', to: 'backoffice#home'
  get '/backoffice/new_conference', to: 'backoffice#new_conference'
  post '/backoffice/new_conference/post', to: 'backoffice#create'
  get '/backoffice/edit/:id', to: 'backoffice#edit'
  post 'backoffice/edit/:id/post', to: 'backoffice#update'
  get '/backoffice/feedbacks/:id', to: 'backoffice#feedbacks'
  get '/backoffice/reservations/:id', to: 'backoffice#reservations'
  get '/backoffice/reservations/delete/:id', to: 'backoffice#delete_reservation'
  get '/backoffice/suggestions/delete/:id', to: 'backoffice#delete_suggestion'
  post '/backoffice/admins/add', to: 'backoffice#add_admin'
  get '/backoffice/admins/revoke/:id', to: 'backoffice#revoke_admin'

end

app/models/conference.rb
class Conference < ActiveRecord::Base

  has_many :reservations
  has_many :users, through: :reservations

  def taken_sits
    users.count
  end

  def free_sits
    sits - taken_sits
  end

end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :user
  belongs_to :topic_suggestion
  validates :user_id, uniqueness: { scope: [:user_id, :topic_suggestion_id], message: 'Vous avez déjà aimé cette suggestion.' }

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :user
  belongs_to :conference

  validates :user_id, uniqueness: { scope: [:user_id, :conference_id], message: 'Vous participez déjà à cette conférence.' }
  validate :conference_still_have_sits

  def conference_still_have_sits
    if conference.taken_sits + 1 > conference.sits
      errors.add :conference, 'Plus aucune place n\'est disponible pour cette conférence.'
    end
  end

end

app/models/topic_suggestion.rb
class TopicSuggestion < ActiveRecord::Base

  has_many :likes
  has_many :users, through: :likes

  validates_presence_of :name, message: 'Merci d\'entrer un nom à votre suggestion.'

  def points
    likes.count
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :likes
  has_many :topic_suggestions, through: :likes
  has_many :reservations
  has_many :conferences, through: :reservations

  validates_uniqueness_of :booster_id,
    message: 'Vous êtes déjà inscrit sur la plateforme. Si vous avez oublié votre mot de passe, contactez un responsable tech\'Lunches sur votre campus.'
  validates_presence_of :first_name, message: 'Merci d\'entrer votre prénom.'
  validates_presence_of :last_name, message: 'Merci d\'entrer votre nom.'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_filter :load_connected_user

  def load_connected_user
    if params[:controller] != 'login'
      if session.has_key? :logged_id
        @logged_user = User.find session[:logged_id]
        unless @logged_user
          redirect_to 'login/form'
        end
      else
        redirect_to 'login/form'
      end
    end
  end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_filter :check_if_admin

  def check_if_admin
    unless @logged_user.is_admin
      redirect_to '/conferences/home'
    end
  end

  def new_conference
    @conference = Conference.new
    render 'backoffice/form'
  end

  def edit
    @conference = Conference.find(params[:id])
    render 'backoffice/form'
  end

  def feedbacks
    @conference = Conference.find(params[:id])
  end

  def reservations
    @conference = Conference.find(params[:id])
  end

  def delete_reservation
    Reservation.find(params[:id]).delete
    redirect_to '/backoffice/home?success=1'
  end

  def delete_suggestion
    TopicSuggestion.find(params[:id]).delete
    redirect_to '/backoffice/home?success=1'
  end

  def add_admin
    u = User.find_by_booster_id(params[:booster_id])
    u.is_admin = true
    u.save
    redirect_to '/backoffice/home?success=1'
  end

  def revoke_admin
    if User.where(is_admin: true).count > 1
      u = User.find(params[:id])
      u.is_admin = false
      u.save
      redirect_to '/backoffice/home?success=1'
    else
      redirect_to '/backoffice/home?error=last_admin'
    end
  end

  def create
    begin
      @conference = Conference.create(params.require(:conference).permit(:title, :subtitle, :speaker, :event_date, :description, :sits))
      redirect_to '/backoffice/home'
    rescue
      @conference = Conference.new(params.require(:conference).permit(:title, :subtitle, :speaker, :event_date, :description, :sits))
      @error = true
      render 'backoffice/form'
    end
  end

  def update
    @conference = Conference.find(params[:id])
    @conference.update(params.require(:conference).permit(:title, :subtitle, :speaker, :event_date, :description, :sits))
    redirect_to '/backoffice/home'
  end

end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController

  def home
    @conferences = Conference.where('event_date > ?', DateTime.now).order(created_at: :desc)
  end

  def details
    @conference = Conference.find_by_id params[:id]
    unless @conference
      raise ActionController::RoutingError.new 'Not Found'
    end
  end

  def toggle_attend
    @conference = Conference.find_by_id(params[:id])
    if @conference.reservations.where(user: @logged_user).count == 0
      Reservation.create user: @logged_user, conference: @conference
    else
      Reservation.where(user_id: @logged_user.id, conference: @conference)[0].delete
    end
    redirect_to "/conferences/#{params[:id]}"
  end

  def feedback
    begin
      @reservation = Reservation.where(user: @logged_user).order(created_at: :desc).first
      if @reservation.conference.event_date < DateTime.now
      else
        @reservation = nil
      end
    rescue
      @reservation = nil
    end
  end

  def feedback_update
    @reservation =  Reservation.where(user: @logged_user).order(created_at: :desc).first
    @reservation.feedback = params[:feedback]
    @reservation.save
    @updated = true
    render 'conferences/feedback'
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def form
    @new_user = User.new
  end

  def dispatcher
    if session.has_key? :logged_id
      redirect_to '/conferences/home'
    else
      redirect_to '/login/form'
    end
  end

  def sign_in
    @new_user = User.new
    error_msg = 'Booster ID ou mot de passe incorrect'
    user = User.find_by_booster_id params[:booster_id]
    if user
      if user.authenticate params[:password]
        session[:logged_id] = user.id
        redirect_to '/conferences/home'
      else
        @error = error_msg
        render 'login/form'
      end
    else
      @error = error_msg
      render 'login/form'
    end
  end

  def sign_out
    session.clear
    redirect_to '/login/form?disconnected=1'
  end

  def sign_up
    @new_user = User.create params.require(:user).permit(:booster_id, :first_name, :last_name, :password, :password_confirmation)
    if @new_user.errors.count > 0
      @error = @new_user.errors.first[1]
      render 'login/form'
    else
      session[:logged_id] = @new_user.id
      redirect_to '/conferences/home'
    end
  end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  def home
    @suggestions = TopicSuggestion.all.sort_by { |ts| -ts.points }
  end

  def new
    TopicSuggestion.create name: params['suggestion_name']
    redirect_to '/suggestions/home?success=1'
  end

  def details
    @suggestion = TopicSuggestion.find_by_id params[:id]
    unless @suggestion
      raise ActionController::RoutingError.new 'Not Found'
    end
  end

  def toggle_like
    @suggestion = TopicSuggestion.find_by_id params[:id]
    if @suggestion.likes.where(user: @logged_user).count == 0
      Like.create(user: @logged_user, topic_suggestion: @suggestion)
    else
      Like.where(user: @logged_user, topic_suggestion: @suggestion)[0].delete
    end
    redirect_to "/suggestions/#{params[:id]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/views/backoffice/feedbacks.erb
<h4>Feedbacks</h4>
<h5><%= @conference.title %></h5>

<% @conference.reservations.each do |reservation| %>
    <% if reservation.feedback %>
        <div class="col-xs-12">
          <span class="color: #AAA;"><%= reservation.user.first_name %> <%= reservation.user.last_name %></span>
          <p><%= reservation.feedback %></p>
          <hr />
        </div>
    <% end %>
<% end %>

app/views/backoffice/form.erb
<div id="backoff_edit">
  <% form_url = params[:action] == 'edit' ? "#{@conference.id}/post" : '/backoffice/new_conference/post/' %>
  <% if @error %>
    <div class="alert alert-danger">Please check fields...</div>
  <% end %>
  <%= form_for @conference, url: form_url, method: :post do |f| %>
      <label>Titre : </label>
      <%= f.text_field :title, class: 'form-control' %>
      <label>Sous-titre : </label>
      <%= f.text_field :subtitle, class: 'form-control' %>
      <label>Intervenant : </label>
      <%= f.text_field :speaker, class: 'form-control' %>
      <label>Description : </label>
      <%= f.text_area :description, class: 'form-control', style: 'height: 100px;' %>
      <label>Date :</label>
      <span style="color: #777;font-size: 11px;">(Format : YYYY-MM-DD HH:MM)</span>
      <%= f.text_field :event_date, class: 'form-control' %>
      <label>Places : </label>
      <%= f.text_field :sits, class: 'form-control' %>
      <div style="text-align: right; margin-top: 10px;">
        <button class="btn btn-success" type="submit">Enregistrer</button>
      </div>
  <% end %>
</div>

app/views/backoffice/home.erb
<% if params['success'] == '1' %>
    <div class="alert alert-success">Action effectuée avec succès !</div>
<% end %>

<% if params['error'] == 'last_admin' %>
    <div class="alert alert-danger">Impossible de supprimer le dernier admin !</div>
<% end %>


<h3>Administrateurs</h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Booster ID</th>
      <th>Nom</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% User.where(is_admin: true).each do |user| %>
    <tr>
      <td><%= user.booster_id %></td>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td>
        <a class="btn btn-danger" href="/backoffice/admins/revoke/<%= user.id %>"><%= fa_icon 'user-times' %>&nbsp;Révoquer</a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h4>Ajouter administrateur</h4>
<%= form_tag '/backoffice/admins/add', method: :post do |f| %>
  <div class="form-group">
    <label>Booster ID : </label>
    <%= text_field_tag :booster_id, nil, class: 'form-control' %>
  </div>
  <div style="text-align: right; margin-top: 10px;">
    <button class="btn btn-success" type="submit"><%= fa_icon 'user-plus' %>&nbsp;Ajouter</button>
  </div>
<% end %>

<h3>Conférences</h3>
<div style="text-align: right">
  <a class="btn btn-success" href="/backoffice/new_conference">Nouvelle conférence</a>
</div>

<table class="table table-bordered table-striped" style="margin-top: 6px;">
  <thead>
    <tr>
      <th>#ID</th>
      <th>Titre</th>
      <th>Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% Conference.all.order(event_date: :desc).each do |conference| %>
    <tr>
      <td><%= conference.id %></td>
      <td><%= conference.title %></td>
      <td><%= conference.event_date.strftime('Le %d/%m/%Y à %R') %></td>
      <td>
        <a class="btn btn-warning" href="/backoffice/edit/<%= conference.id %>"><%= fa_icon 'edit' %>&nbsp;Editer</a>
        <a class="btn btn-primary" href="/backoffice/reservations/<%= conference.id %>"><%= fa_icon 'users' %>&nbsp;Réservations</a>
        <a class="btn btn-primary" href="/backoffice/feedbacks/<%= conference.id %>"><%= fa_icon 'comment' %>&nbsp;Feedbacks</a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/backoffice/reservations.erb
<h4>Réservations</h4>
<h5><%= @conference.title %></h5>

<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>#ID</th>
    <th>Etudiant</th>
    <th>Date inscription</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @conference.reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.id %></td>
        <td>(<%= reservation.user.booster_id %>) <%= reservation.user.first_name %> <%= reservation.user.last_name %></td>
        <td><%= reservation.created_at.strftime('Le %d/%m/%Y à %R:%S') %></td>
        <td>
          <a class="btn btn-danger" href="/backoffice/reservations/delete/<%= reservation.id %>"><%= fa_icon 'trash' %>&nbsp;Supprimer</a>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/conferences/details.erb
<div id="event_flyer" class="col-xs-12 col-sm-6">
  <div id="flyer">
    <div id="tl_logo">
      <%= image_tag 'logo.png' %>
      <br>
      <h1><%= @conference.title %></h1>
      <h2><%= @conference.subtitle %></h2>
      <div class="speaker">Par <%= @conference.speaker %></div>
    </div>
  </div>
</div>

<div id="event_meta" class="col-xs-12 col-sm-6">
  <h3><%= @conference.title %></h3>
  <h4><%= @conference.subtitle %></h4>
  <h5>Par <%= @conference.speaker %></h5>
  <h6>Description :</h6>
  <p id="event_desc">
    <%= @conference.description %>
  </p>
  <h6>Places :</h6>
  <span style="color: #666; font-size: 12px;">Places restantes : <%= @conference.free_sits %>/<%= @conference.sits %></span>
  <div class="progress">
    <%
       percent = if @conference.sits > 0
                  (@conference.taken_sits.to_f/@conference.sits.to_f*100).round
                 else
                   0
                 end
    %>
    <div class="progress-bar progress-bar-success" style="width: <%= percent %>%">
      <span class="sr-only"></span>
    </div>
  </div>
  <div style="text-align: right;">
    <% if @conference.reservations.where(user: @logged_user).count == 0 %>
        <a class="btn btn-success" href="/conferences/<%= @conference.id %>/toggle_attend">Participer</a>
    <% else %>
        <a class="btn btn-danger" href="/conferences//<%= @conference.id %>/toggle_attend">Ne plus participer</a>
    <% end %>
  </div>
</div>

app/views/conferences/feedback.erb
<% if @updated %>
    <div class="alert alert-success" role="alert">
      Merci pour votre feedback, il a été pris en compte.
    </div>
<% end %>

<% if @reservation %>
    <h3>Laissez un avis sur la dernière conférence !</h3>
    <h4><%= @reservation.conference.title %></h4>
    <%= form_tag '/conferences/feedback', method: :post do %>
        <textarea name="feedback" class="form-control" style="height: 200px;"><%= @reservation.feedback %></textarea>
        <div style="text-align: right;margin-top: 5px;">
          <button type="submit" class="btn btn-success">Commenter</button>
        </div>
    <% end %>
<% else %>
  <div style="text-align: center">
    <h1><%= fa_icon 'comment' %>&nbsp;Vous n'avez pas participé à une conférence dernièrement.</h1>
  </div>
<% end %>

app/views/conferences/home.erb
<% @conferences.each do |conference| %>
    <h4><%= conference.event_date.strftime('Le %d/%m/%Y à %R') %></h4>
    <div class="event_item row">
      <div class="col-sm-6 col-xs-12 event_title">
        <a href="/conferences/<%= conference.id %>"><%= conference.title %></a>
      </div>
      <div class="col-sm-6 col-xs-12">
        <strong>Places restantes : </strong> : <%= conference.sits == 0 ? 'Inscriptions non-ouvertes' : "#{conference.free_sits} / #{conference.sits}" %>
      </div>
      <div class="col-sm-6 col-xs-12">
        <strong>Intervenant</strong> : <%= conference.speaker %>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tech'Lunches</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if params[:controller] != 'login' %>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/conferences/home">tech'Lunches</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/conferences/home"><%= fa_icon 'calendar' %>&nbsp;Calendrier</a></li>
              <li><a href="/conferences/feedback"><%= fa_icon 'comment' %>&nbsp;Feedback</a></li>
              <li><a href="/suggestions/home"><%= fa_icon 'thumbs-up' %>&nbsp;Suggestions</a></li>
              <% if @logged_user.is_admin %>
              <li><a href="/backoffice/home"><%= fa_icon 'cog' %>&nbsp;Back office</a></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/logout"><%= fa_icon 'sign-out' %>&nbsp;Déconnexion</a></li>
            </ul>
          </div>
        </div>
      </nav>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/login/form.erb
<div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4" id="login">

  <div class="row" style="margin-top: 15px; margin-bottom: 15px; text-align: center;">
    <%= image_tag 'logo.png', id: 'logo' %>
  </div>

  <% if @error %>
    <div class="alert alert-danger" role="alert"><%= @error %></div>
  <% end %>

  <ul class="nav nav-tabs nav-justified" style="margin-bottom: 10px;">
    <li class="active"><a data-toggle="tab" href="#signin">Se connecter</a></li>
    <li><a data-toggle="tab" href="#signup">S'inscrire</a></li>
  </ul>

  <div class="tab-content">
    <div id="signin" class="tab-pane fade in active">
      <%= form_tag '/login/sign_in', method: :post do %>
        <div class="form-group">
          <label>Booster ID : </label>
          <%= text_field_tag :booster_id, nil, class: 'form-control', placeholder: 'Booster ID'  %>
        </div>
        <div class="form-group">
          <label>Mot de passe : </label>
          <%= password_field_tag :password, nil, class: 'form-control', placeholder: 'Mot de passe' %>
        </div>
        <div style="text-align: right;">
          <button class="btn btn-success"><%= fa_icon 'sign-in' %>&nbsp;&nbsp;Se connecter</button>
        </div>
      <% end %>
    </div>
    <div id="signup" class="tab-pane fade">
      <%= form_for @new_user, url: '/login/sign_up', method: 'post' do |f| %>
        <div class="form-group">
          <label>Booster ID : </label>
          <%= f.text_field :booster_id, class: 'form-control', placeholder: '844242'  %>
        </div>
        <div class="form-group">
          <label>Prénom : </label>
          <%= f.text_field :first_name, class: 'form-control', placeholder: 'Arthur'  %>
        </div>
        <div class="form-group">
          <label>Nom : </label>
          <%= f.text_field :last_name, class: 'form-control', placeholder: 'Dent'  %>
        </div>
        <div class="form-group">
          <label>Mot de passe : </label>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Mot de passe' %>
        </div>
        <div class="form-group">
          <label>Confirmer le mot de passe : </label>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirmer mot de passe' %>
        </div>
        <div style="text-align: right;">
          <button class="btn btn-success"><%= fa_icon 'user-plus' %>&nbsp;&nbsp;S'inscrire</button>
        </div>
      <% end %>
    </div>
  </div>



</div>

app/views/suggestions/details.erb
<div style="text-align: center">
  <h1><%= @suggestion.name %></h1>
  <hr />
  <% if @suggestion.likes.where(user: @logged_user).count == 0 %>
  <a href="/suggestions/<%= @suggestion.id %>/toggle_like" class="btn btn-success">
    <%= fa_icon 'thumbs-up' %>&nbsp;&nbsp;L'idée d'une conférence sur ce thème me plait !
  </a>
  <% else %>
  <a href="/suggestions/<%= @suggestion.id %>/toggle_like" class="btn btn-danger">
    <%= fa_icon 'thumbs-down' %>&nbsp;&nbsp;L'idée d'une conférence sur ce thème ne me plait plus !
  </a>
  <% end %>
  <% if @logged_user.is_admin %>
  <br><br>
  <a  class="btn btn-danger" href="/backoffice/suggestions/delete/<%= @suggestion.id %>"><%= fa_icon 'trash' %>&nbsp;Supprimer suggestion</a>
  <% end %>
</div>

app/views/suggestions/home.erb
<h2>Suggestions d'idées</h2>

<% if params[:success] %>
    <div class="alert alert-success" role="alert">
      Merci pour votre suggestion !
    </div>
<% end %>

<div class="row">
  <h4>Faire une suggestion :</h4>
  <%= form_tag '/suggestions/new', method: :post do %>
      <input type="text" name="suggestion_name" class="form-control" />
      <div style="text-align: right; margin-top: 3px;">
        <button class="btn btn-success">Proposer</button>
      </div>
  <% end %>
</div>

<div class="row">
  <h4>Toutes les suggestions :</h4>
  <ul class="col-xs-12" id="topic_suggestions">
    <% @suggestions.each do |suggestion| %>
    <li class="col-xs-12">
      <span class="suggestion_point"><%= suggestion.points %></span> -
      <a href="/suggestions/<%= suggestion.id %>"><%= suggestion.name %></a>
    </li>
    <% end %>
  </ul>
</div>